development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: data_engineering_development
  pool: 5
  username: root
  password:
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: data_engineering_test
  pool: 5
  username: root
  password:
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: data_engineering_production
  pool: 5
  username: data_engineering_user
  password: thisisnotit
  socket: /tmp/mysql.sock
  #host: localhost
